stages:
  - test

test_proyect:
    stage: test
    image: bitnami/dotnet-sdk:6.0.420
    services:
      - name: redis:latest
        alias: localhost
    before_script:
        - dotnet restore
        - dotnet build
    script:
        - dotnet test
        - dotnet test

        
