version: '3.4'

services:
  customeroperationsapi:
    container_name: "server"
    image: frandelartifact/customers-api
    build: 
        context: .
        dockerfile: ./src/CustomerOperationsApi/
    ports:
      - "5000:5000"
      - "5001:5001"
  redis:
    container_name: "redis_db"
    image: redis
    ports: 
      - "6379:6379"

  web:
    container_name: "web-front"
    image: "frandelartifact/customer-op-static-front"
    ports:
      - "8080:80"
    build: ./src/CustomerOperations-Frontend/